stage('Build Frontend Docker Image') {
    steps {
        script {
            sh "docker build -t lalithaditya07/frontend:latest ./frontend"
        }
    }
}

stage('Push Frontend to Docker Hub') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
            script {
                sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                sh "docker push $DOCKER_USER/frontend:latest"
            }
        }
    }
}
